In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [6]:
file_path1 = Path('../data/raw/autoscout24_2021.csv')
file_path2 = Path('../data/raw/autoscout24_2022.csv')
file_path3 = Path('../data/raw/autoscout24_2023.csv')
file_path4 = Path('../data/raw/autoscout24_2024.csv')
file_path5 = Path('../data/raw/autoscout24_full.csv')

In [7]:
df1 = pd.read_csv(file_path1, sep=';')
df2 = pd.read_csv(file_path2, sep=';')
df3 = pd.read_csv(file_path3, sep=';')
df4 = pd.read_csv(file_path4, sep=';')
df5 = pd.read_csv(file_path5, sep=';')

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208304 entries, 0 to 208303
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Index                    208304 non-null  int64
 1   Price                    208304 non-null  int64
 2   Currency                 208304 non-null  object
 3   Condition                208304 non-null  object
 4   Vehicle_brand            208304 non-null  object
 5   Vehicle_model            208304 non-null  object
 6   Vehicle_version          138082 non-null  object
 7   Vehicle_generation       147860 non-null  object
 8   Production_year          208304 non-null  int64
 9   Mileage_km               207321 non-null  float64
 10  Power_HP                 207661 non-null  float64
 11  Displacement_cm3         206338 non-null  float64
 12  Fuel_type                208304 non-null  object
 13  CO2_emissions            94047 non-null   float64
 14  Drive                    193228 non-null  object
 15  Transmission             207825 non-null  object
 16  Type                     208304 non-null  object
 17  Doors_number             206817 non-null  float64
 18  Colour                   208304 non-null  object
 19  country                  118312 non-null  object
 20  First_owner              65094 non-null   object
 21  First_registration_date  86445 non-null   object
 22  Offer_publication_date   208304 non-null  object
 23  Offer_location           208304 non-null  object
 24  Features                 208304 non-null  object
dtypes: float64(5), int64(3), object(17)
memory usage: 39.7+ MB

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29479 entries, 0 to 29478
Data columns (total 45 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28570 non-null  object
 1   short_description        28358 non-null  object
 2   make                     28570 non-null  object
 3   model                    28297 non-null  object
 4   location                 28570 non-null  object
 5   price                    28570 non-null  float64
 6   body_type                28570 non-null  object
 7   type                     28570 non-null  object
 8   doors                    28213 non-null  float64
 9   country                  16832 non-null  object
 10  offer_number             23065 non-null  object
 11  warranty                 15771 non-null  object
 12  mileage                  28569 non-null  float64
 13  first_registration       28568 non-null  float64
 14  gearbox                  28322 non-null  object
 15  fuel_type                26784 non-null  object
 16  colour                   26849 non-null  object
 17  paint                    14470 non-null  object
 18  desc                     27897 non-null  object
 19  seller                   28570 non-null  object
 20  seats                    25447 non-null  float64
 21  power                    27999 non-null  float64
 22  engine_size              27173 non-null  float64
 23  gears                    18923 non-null  float64
 24  co_emissions             18573 non-null  float64
 25  manufacturer_colour      21760 non-null  object
 26  drivetrain               16856 non-null  object
 27  cylinders                18818 non-null  float64
 28  fuel_consumption         23362 non-null  float64
 29  comfort_&_convenience    25388 non-null  object
 30  entertainment_&_media    23599 non-null  object
 31  safety_&_security        25367 non-null  object
 32  extras                   23428 non-null  object
 33  empty_weight             17734 non-null  float64
 34  model_code               8347 non-null   object
 35  general_inspection       12225 non-null  object
 36  full_service_history     12544 non-null  object
 37  non_smoker_vehicle       11560 non-null  object
 38  emission_class           17830 non-null  object
 39  emissions_sticker        9387 non-null   object
 40  upholstery_colour        14517 non-null  object
 41  upholstery               18552 non-null  object
 42  previous_owner           13973 non-null  object
 43  energy_efficiency_class  7793 non-null   object
 44  co_efficiency            7793 non-null   object
dtypes: float64(12), object(33)
memory usage: 10.1+ MB

In [10]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100659 entries, 0 to 100658
Data columns (total 24 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Unnamed: 0                                100659 non-null  int64
 1   Brand                                     100659 non-null  object
 2   Price                                     100659 non-null  float64
 3   Carrosserie                               100659 non-null  object
 4   État                                      100659 non-null  object
 5   Portes                                    100659 non-null  float64
 6   Kilométrage                               100659 non-null  int64
 7   Année                                     100659 non-null  float64
 8   Transmission                              100659 non-null  object
 9   Carburant                                 100659 non-null  object
 10  Couleur extérieure                        100659 non-null  object
 11  Accoudoir                                 100659 non-null  bool
 12  Assistant de démarrage en côte            100659 non-null  bool
 13  Capteurs d'aide au stationnement arrière  100659 non-null  bool
 14  Capteurs d'aide au stationnement avant    100659 non-null  bool
 15  Climatisation                             100659 non-null  bool
 16  Climatisation automatique                 100659 non-null  bool
 17  Start/Stop automatique                    100659 non-null  bool
 18  Système de navigation                     100659 non-null  bool
 19  Volant en cuir                            100659 non-null  bool
 20  Volant multifonctions                     100659 non-null  bool
 21  Country                                   100659 non-null  object
 22  ModelC                                    100659 non-null  object
 23  Puissance kW                              100659 non-null  int64
dtypes: bool(10), float64(3), int64(3), object(8)
memory usage: 11.7+ MB

In [11]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  40494 non-null  object
 1   Model                 40273 non-null  object
 2   Body                  40493 non-null  object
 3   Mileage_km            40494 non-null  int64
 4   Price                 40494 non-null  int64
 5   Year                  38799 non-null  float64
 6   Country               37902 non-null  object
 7   Condition             40494 non-null  object
 8   Fuel_Type             40465 non-null  object
 9   Fuel_Consumption_l    12773 non-null  float64
 10  Drivetrain            31860 non-null  object
 11  Gearbox               40014 non-null  object
 12  Gears                 25115 non-null  float64
 13  Power_hp              40494 non-null  int64
 14  Engine_Size_cc        34564 non-null  float64
 15  Cylinders             30332 non-null  float64
 16  Seats                 38697 non-null  float64
 17  Doors                 39517 non-null  float64
 18  Color                 37919 non-null  object
 19  Upholstery            33222 non-null  object
 20  Full_Service_History  40494 non-null  bool
 21  Non_Smoker_Vehicle    40494 non-null  bool
 22  Previous_Owners       22271 non-null  float64
 23  Seller                40344 non-null  object
 24  Image_url             40494 non-null  object
dtypes: bool(2), float64(8), int64(3), object(12)
memory usage: 7.2+ MB

In [12]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118382 entries, 0 to 118381
Data columns (total 75 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   id                                    118382 non-null  object
 1   description                           113990 non-null  object
 2   ratings_average                       76428 non-null   object
 3   ratings_count                         76428 non-null   float64
 4   ratings_recommend_percentage          76428 non-null   float64
 5   price_currency                        118382 non-null  object
 6   price                                 118382 non-null  float64
 7   price_tax_deductible                  118382 non-null  bool
 8   price_negotiable                      118382 non-null  bool
 9   price_net                             34016 non-null   float64
 10  price_vat_rate                        30379 non-null   float64
 11  vin                                   40222 non-null   object
 12  make                                  118382 non-null  object
 13  model                                 116980 non-null  object
 14  model_version                         117544 non-null  object
 15  german_hsn_tsn                        30811 non-null   object
 16  mileage_km_raw                        117738 non-null  float64
 17  mileage_km                            117738 non-null  object
 18  registration_date                     118161 non-null  object
 19  production_year                       22272 non-null   float64
 20  vehicle_type                          118382 non-null  object
 21  body_type                             118382 non-null  object
 22  nr_seats                              113476 non-null  float64
 23  nr_doors                              116929 non-null  float64
 24  body_color                            106471 non-null  object
 25  paint_type                            92335 non-null   object
 26  body_color_original                   74050 non-null   object
 27  upholstery                            91637 non-null   object
 28  upholstery_color                      85897 non-null   object
 29  power_kw                              116770 non-null  float64
 30  power_hp                              116770 non-null  float64
 31  transmission                          117566 non-null  object
 32  gears                                 75134 non-null   float64
 33  drive_train                           90629 non-null   object
 34  cylinders                             93524 non-null   float64
 35  cylinders_volume_cc                   106096 non-null  float64
 36  weight_kg                             94296 non-null   object
 37  has_particle_filter                   118382 non-null  bool
 38  fuel_category                         118309 non-null  object
 39  primary_fuel                          59973 non-null   object
 40  electric_range_km                     12745 non-null   float64
 41  electric_range_city_km                639 non-null     float64
 42  fuel_cons_comb_l100_km                41844 non-null   float64
 43  fuel_cons_city_l100_km                0 non-null       float64
 44  fuel_cons_highway_l100_km             0 non-null       float64
 45  co2_emission_grper_km                 24811 non-null   float64
 46  fuel_cons_comb_l100_wltp_km           30270 non-null   float64
 47  fuel_cons_electric_comb_l100_wltp_km  4926 non-null    float64
 48  co2_emission_grper_wltp_km            46455 non-null   float64
 49  equipment_comfort                     118382 non-null  object
 50  equipment_entertainment               118382 non-null  object
 51  equipment_extra                       118382 non-null  object
 52  equipment_safety                      118382 non-null  object
 53  is_used                               118382 non-null  bool
 54  is_new                                118382 non-null  bool
 55  is_preregistered                      118382 non-null  bool
 56  had_accident                          118382 non-null  bool
 57  has_full_service_history              118382 non-null  bool
 58  non_smoking                           118382 non-null  bool
 59  nr_prev_owners                        64814 non-null   float64
 60  is_rental                             118382 non-null  bool
 61  envir_standard                        77121 non-null   object
 62  original_market                       45616 non-null   object
 63  offer_type                            118382 non-null  object
 64  country_code                          118367 non-null  object
 65  zip                                   118363 non-null  object
 66  city                                  118274 non-null  object
 67  street                                98054 non-null   object
 68  latitude                              117993 non-null  float64
 69  longitude                             117993 non-null  float64
 70  seller_is_dealer                      118382 non-null  bool
 71  seller_type                           118367 non-null  object
 72  seller_company_name                   98565 non-null   object
 73  has_warranty                          0 non-null       float64
 74  warranty                              0 non-null       float64
dtypes: bool(11), float64(28), object(36)
memory usage: 59.0+ MB

In [13]:
cols = [
    "make", "model", "price", "year", "mileage",
    "fuel", "transmission", "power_hp",
    "engine_cc", "doors", "country"
]

In [14]:
import pandas as pd
import numpy as np

# --- helper: kW → HP ---
def kw_to_hp(x):
    return x * 1.341 if pd.notnull(x) else np.nan

# =======================
# DF1
# =======================
df1_ = df1.rename(columns={
    "Vehicle_brand": "make",
    "Vehicle_model": "model",
    "Price": "price",
    "Production_year": "year",
    "Mileage_km": "mileage",
    "Fuel_type": "fuel",
    "Transmission": "transmission",
    "Power_HP": "power_hp",
    "Displacement_cm3": "engine_cc",
    "Doors_number": "doors",
    "country": "country"
})

df1_ = df1_[["make","model","price","year","mileage","fuel",
             "transmission","power_hp","engine_cc","doors","country"]]


# =======================
# DF2
# =======================
df2_ = df2.rename(columns={
    "make": "make",
    "model": "model",
    "price": "price",
    "first_registration": "year",
    "mileage": "mileage",
    "fuel_type": "fuel",
    "gearbox": "transmission",
    "power": "power_hp",
    "engine_size": "engine_cc",
    "doors": "doors",
    "country": "country"
})

df2_ = df2_[["make","model","price","year","mileage","fuel",
             "transmission","power_hp","engine_cc","doors","country"]]


# =======================
# DF3
# =======================
df3_ = df3.rename(columns={
    "Brand": "make",
    "ModelC": "model",
    "Price": "price",
    "Année": "year",
    "Kilométrage": "mileage",
    "Carburant": "fuel",
    "Transmission": "transmission",
    "Puissance kW": "power_kw",
    "Portes": "doors",
    "Country": "country"
})

df3_["power_hp"] = df3_["power_kw"].apply(kw_to_hp)
df3_["engine_cc"] = np.nan

df3_ = df3_[["make","model","price","year","mileage","fuel",
             "transmission","power_hp","engine_cc","doors","country"]]


# =======================
# DF4
# =======================
df4_ = df4.rename(columns={
    "Make": "make",
    "Model": "model",
    "Price": "price",
    "Year": "year",
    "Mileage_km": "mileage",
    "Fuel_Type": "fuel",
    "Gearbox": "transmission",
    "Power_hp": "power_hp",
    "Engine_Size_cc": "engine_cc",
    "Doors": "doors",
    "Country": "country"
})

df4_ = df4_[["make","model","price","year","mileage","fuel",
             "transmission","power_hp","engine_cc","doors","country"]]


# =======================
# DF5
# =======================
df5_ = df5.rename(columns={
    "make": "make",
    "model": "model",
    "price": "price",
    "production_year": "year",
    "mileage_km_raw": "mileage",
    "fuel_category": "fuel",
    "transmission": "transmission",
    "power_hp": "power_hp",
    "cylinders_volume_cc": "engine_cc",
    "nr_doors": "doors",
    "country_code": "country"
})

df5_ = df5_[["make","model","price","year","mileage","fuel",
             "transmission","power_hp","engine_cc","doors","country"]]


# =======================
# CONCAT ALL
# =======================
final_df = pd.concat([df1_, df2_, df3_, df4_, df5_], ignore_index=True)


# =======================
# CLEANING (optional but recommended)
# =======================
# normalize text
final_df["make"] = final_df["make"].str.lower()
final_df["model"] = final_df["model"].str.lower()
final_df["fuel"] = final_df["fuel"].str.lower()
final_df["transmission"] = final_df["transmission"].str.lower()

# convert types
final_df["year"] = pd.to_numeric(final_df["year"], errors="coerce")
final_df["price"] = pd.to_numeric(final_df["price"], errors="coerce")
final_df["mileage"] = pd.to_numeric(final_df["mileage"], errors="coerce")

# drop obvious garbage rows
final_df = final_df.dropna(subset=["price", "make", "model"])

# reset index
final_df = final_df.reset_index(drop=True)

print(final_df.shape)
final_df.head()

(494513, 11)

,make,model,price,year,mileage,fuel,transmission,power_hp,engine_cc,doors,country
0,abarth,595,86200.0,2021.0,1.0,gasoline,manual,145.0,1400.0,3.0,NaN
1,abarth,other,43500.0,1974.0,59000.0,gasoline,manual,75.0,1100.0,2.0,NaN
2,abarth,500,44900.0,2018.0,52000.0,gasoline,automatic,180.0,1368.0,3.0,NaN
3,abarth,500,39900.0,2012.0,29000.0,gasoline,manual,160.0,1368.0,3.0,NaN
4,abarth,595,97900.0,2021.0,600.0,gasoline,manual,165.0,1368.0,3.0,NaN

In [15]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494513 entries, 0 to 494512
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   make          494513 non-null  object
 1   model         494513 non-null  object
 2   price         494513 non-null  float64
 3   year          397719 non-null  float64
 4   mileage       492945 non-null  float64
 5   fuel          492647 non-null  object
 6   transmission  492547 non-null  object
 7   power_hp      491727 non-null  float64
 8   engine_cc     372817 non-null  float64
 9   doors         490328 non-null  float64
 10  country       390309 non-null  object
dtypes: float64(6), object(5)
memory usage: 41.5+ MB

In [16]:
final_df['make'].value_counts()

make
bmw                55396
mercedes-benz      34097
audi               32876
porsche            27387
volkswagen         19594
                   ...
militem                1
nsu                    1
hyundai                1
caravans-wohnm         1
mitsubishi             1
Name: count, Length: 171, dtype: int64

In [17]:
final_df['country'].value_counts()

country
Germany           67386
DE                60225
Poland            57158
NL                38074
IT                33670
France            21786
Belgium           17743
Italy             17412
Austria           15907
BE                13291
ES                 9808
AT                 8405
FR                 7383
Spain              6399
United States      4099
luxembourg         2623
Switzerland        2161
Netherlands        2094
LU                  890
Sweden              739
Denmark             682
Canada              597
Other               378
European Union      339
Czech Republic      259
Luxembourg          219
Great Britain       219
Finland              62
Slovakia             52
Czechia              47
Norway               46
Slovenia             27
Hungary              26
Russia               18
Romania              15
Japan                12
Estonia               9
Ireland               8
Greece                7
Ukraine               6
Croatia               5
Lithuania             5
Monaco                4
Belarus               3
Bulgaria              2
Iceland               2
Turkey                2
Latvia                2
Liechtenstein         1
Malta                 1
Mexico                1
Name: count, dtype: int64

In [27]:
df = final_df.rename(columns={'make': 'car_brand'})

In [28]:
df

,car_brand,model,price,year,mileage,fuel,transmission,power_hp,engine_cc,doors,country
0,abarth,595,86200.0,2021.0,1.0,gasoline,manual,145.0,1400.0,3.0,NaN
1,abarth,other,43500.0,1974.0,59000.0,gasoline,manual,75.0,1100.0,2.0,NaN
2,abarth,500,44900.0,2018.0,52000.0,gasoline,automatic,180.0,1368.0,3.0,NaN
3,abarth,500,39900.0,2012.0,29000.0,gasoline,manual,160.0,1368.0,3.0,NaN
4,abarth,595,97900.0,2021.0,600.0,gasoline,manual,165.0,1368.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
494508,bmw,m4,49500.0,NaN,90000.0,gasoline,semi-automatic,431.0,2979.0,2.0,IT
494509,bmw,x5,91889.0,NaN,33000.0,electric/gasoline,automatic,489.0,2998.0,5.0,DE
494510,bmw,235,32900.0,NaN,43000.0,gasoline,automatic,306.0,1998.0,4.0,DE
494511,bmw,840,57000.0,NaN,61000.0,gasoline,automatic,340.0,2998.0,4.0,DE
494512,bmw,730,29500.0,NaN,298000.0,diesel,semi-automatic,265.0,2993.0,4.0,IT

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494513 entries, 0 to 494512
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   car_brand     494513 non-null  object
 1   model         494513 non-null  object
 2   price         494513 non-null  float64
 3   year          397719 non-null  float64
 4   mileage       492945 non-null  float64
 5   fuel          492647 non-null  object
 6   transmission  492547 non-null  object
 7   power_hp      491727 non-null  float64
 8   engine_cc     372817 non-null  float64
 9   doors         490328 non-null  float64
 10  country       390309 non-null  object
dtypes: float64(6), object(5)
memory usage: 41.5+ MB

In [30]:
df.to_parquet('../data/consolidated.parquet')

In [31]:
from sklearn.model_selection import train_test_split

# 60% train, 40% temp
df_train, df_temp = train_test_split(df, test_size=0.4, random_state=123)

# split temp into 20% valid, 20% test
df_valid, df_test = train_test_split(df_temp, test_size=0.5, random_state=123)

In [38]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

def evaluate_model(model, X, y):
    y_pred = model.predict(X)
    
    mae = mean_absolute_error(y, y_pred)
    rmse = np.sqrt(mean_squared_error(y, y_pred))
    
    # avoid division by zero
    mape = np.mean(np.abs((y - y_pred) / np.clip(y, 1e-8, None))) * 100
    smape = np.mean(2 * np.abs(y - y_pred) / (np.abs(y) + np.abs(y_pred) + 1e-8)) * 100
    
    print(f"MAE  : {mae:.2f}")
    print(f"RMSE : {rmse:.2f}")
    print(f"MAPE : {mape:.2f}%")
    print(f"SMAPE: {smape:.2f}%")
    
    return {"mae": mae, "rmse": rmse, "mape": mape, "smape": smape}

## Train Dataset

In [41]:
X_train = df_train.drop(columns=['price'])
y_train = df_train['price']

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

num_cols = X_train.select_dtypes(include=['float64','int64']).columns
cat_cols = X_train.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer([
    ('num', SimpleImputer(strategy='median'), num_cols),
    ('cat', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]), cat_cols)
])

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

xgb_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', XGBRegressor(
        objective='reg:squarederror',
        tree_method='hist',
        n_jobs=-1,
        random_state=123
    ))
])

param_grid = {
    'model__n_estimators': [300, 500],
    'model__learning_rate': [0.03, 0.1],
    'model__max_depth': [4, 6],
    'model__subsample': [0.8, 1.0],
    'model__colsample_bytree': [0.8, 1.0],
    'model__min_child_weight': [1, 5],
    'model__gamma': [0, 0.5],
    'model__reg_alpha': [0, 0.01],
    'model__reg_lambda': [1, 3]
}

xgb_grid_search = GridSearchCV(
    xgb_pipeline,
    param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

xgb_grid_search.fit(X_train, y_train)

model_xgb_best = xgb_grid_search.best_estimator_

print("Best params:", xgb_grid_search.best_params_)
print("Best MAE:", -xgb_grid_search.best_score_)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

gbr_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', GradientBoostingRegressor(random_state=123))
])

param_grid = {
    'model__n_estimators': [200, 300],
    'model__learning_rate': [0.03, 0.1],
    'model__max_depth': [3, 4],
    'model__min_samples_split': [2, 10],
    'model__min_samples_leaf': [1, 2],
    'model__subsample': [0.8, 1.0]
}

gbr_grid_search = GridSearchCV(
    gbr_pipeline,
    param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

gbr_grid_search.fit(X_train, y_train)

model_gbr_best = gbr_grid_search.best_estimator_

print("Best params:", gbr_grid_search.best_params_)
print("Best MAE:", -gbr_grid_search.best_score_)

In [ ]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

stack_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', StackingRegressor(
        estimators=[
            ('gbr', model_gbr_best.named_steps['model']),
            ('xgb', model_xgb_best.named_steps['model'])
        ],
        final_estimator=LinearRegression(),
        n_jobs=-1,
        passthrough=False
    ))
])

param_grid = {
    'model__final_estimator__fit_intercept': [True, False]
}

stack_grid_search = GridSearchCV(
    stack_pipeline,
    param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

stack_grid_search.fit(X_train, y_train)

model_stacking_best = stack_grid_search.best_estimator_

print("Best params:", stack_grid_search.best_params_)
print("Best MAE:", -stack_grid_search.best_score_)

## Valid Dataset

In [40]:
X_valid = df_valid.drop(columns=['price'])
y_valid = df_valid['price']

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

num_cols = X_train.select_dtypes(include=['float64','int64']).columns
cat_cols = X_train.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer([
    ('num', SimpleImputer(strategy='median'), num_cols),
    ('cat', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]), cat_cols)
])

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

xgb_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', XGBRegressor(
        objective='reg:squarederror',
        tree_method='hist',
        n_jobs=-1,
        random_state=123
    ))
])

param_grid = {
    'model__n_estimators': [300, 500],
    'model__learning_rate': [0.03, 0.1],
    'model__max_depth': [4, 6],
    'model__subsample': [0.8, 1.0],
    'model__colsample_bytree': [0.8, 1.0],
    'model__min_child_weight': [1, 5],
    'model__gamma': [0, 0.5],
    'model__reg_alpha': [0, 0.01],
    'model__reg_lambda': [1, 3]
}

xgb_grid_search = GridSearchCV(
    xgb_pipeline,
    param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

xgb_grid_search.fit(X_valid, y_valid)

model_xgb_best = xgb_grid_search.best_estimator_

print("Best params:", xgb_grid_search.best_params_)
print("Best MAE:", -xgb_grid_search.best_score_)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

gbr_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', GradientBoostingRegressor(random_state=123))
])

param_grid = {
    'model__n_estimators': [200, 300],
    'model__learning_rate': [0.03, 0.1],
    'model__max_depth': [3, 4],
    'model__min_samples_split': [2, 10],
    'model__min_samples_leaf': [1, 2],
    'model__subsample': [0.8, 1.0]
}

gbr_grid_search = GridSearchCV(
    gbr_pipeline,
    param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

gbr_grid_search.fit(X_valid, y_valid)

model_gbr_best = gbr_grid_search.best_estimator_

print("Best params:", gbr_grid_search.best_params_)
print("Best MAE:", -gbr_grid_search.best_score_)

In [ ]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

stack_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model', StackingRegressor(
        estimators=[
            ('gbr', model_gbr_best.named_steps['model']),
            ('xgb', model_xgb_best.named_steps['model'])
        ],
        final_estimator=LinearRegression(),
        n_jobs=-1,
        passthrough=False
    ))
])

param_grid = {
    'model__final_estimator__fit_intercept': [True, False]
}

stack_grid_search = GridSearchCV(
    stack_pipeline,
    param_grid,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

stack_grid_search.fit(X_valid, y_valid)

model_stacking_best = stack_grid_search.best_estimator_

print("Best params:", stack_grid_search.best_params_)
print("Best MAE:", -stack_grid_search.best_score_)

## Test Dataset

In [39]:
X_test = df_test.drop(columns=['price'])
y_test = df_test['price']

In [ ]:
evaluate_model(model_stacking_best, X_test, y_test)